In [6]:
from IPython.display import display
import pandas as pd
import re
import requests
from bs4 import BeautifulSoup

r = requests.get("https://books.toscrape.com/")
soup = BeautifulSoup(r.content,'lxml')


print(r.status_code)

book_details = soup.find_all('article', attrs={'class':'product_pod'})
print(len(book_details))

def get_book_detail(book_details):
    title = book_details.find('h3').find('a')['title']
    price = book_details.find('p', attrs={'class':'price_color'}).text
    rating = book_details.find('p', attrs={'class':'star-rating'})['class'][-1]
    return title,price,rating
print(get_book_detail(book_details[0]))
b = get_book_detail(book_details[1])

def fix_price(price):
    c_price = float(re.sub('[^0-9.]',"",price))
    return c_price
print(fix_price(b[1]))

def fix_rating(rating):
    map_rating = {'One':1,
                  'Two':2,
                  'Three':3,
                  'Four':4,
                  'Five':5,
                  'Six':6}
    return map_rating[rating]
print(fix_rating(b[-1]))

def get_book_detail(book_details):
    title = book_details.find('h3').find('a')['title']
    price = book_details.find('p', attrs={'class':'price_color'}).text
    rating = book_details.find('p', attrs={'class':'star-rating'})['class'][-1]
    return {'title':title,
            'price':fix_price(price),
            'rating':fix_rating(rating)}
bd = get_book_detail(book_details[0])
print(bd)

All_detail = [get_book_detail(book_detail) for book_detail in book_details]
# for detail in All_detail:
#     print(detail)

df = pd.DataFrame(All_detail)

display(df)

200
20
('A Light in the Attic', 'Â£51.77', 'Three')
53.74
1
{'title': 'A Light in the Attic', 'price': 51.77, 'rating': 3}

                                                title  price  rating
0                                A Light in the Attic  51.77       3
1                                  Tipping the Velvet  53.74       1
2                                          Soumission  50.10       1
3                                       Sharp Objects  47.82       4
4               Sapiens: A Brief History of Humankind  54.23       5
5                                     The Requiem Red  22.65       1
6   The Dirty Little Secrets of Getting Your Dream...  33.34       4
7   The Coming Woman: A Novel Based on the Life of...  17.93       3
8   The Boys in the Boat: Nine Americans and Their...  22.60       4
9                                     The Black Maria  52.15       1
10     Starving Hearts (Triangular Trade Trilogy, #1)  13.99       2
11                              Shakespeare's Sonnets  20.66       4
12                                        Set Me Free  17.46       5
13  Scott Pilgrim's Precious Little Life (Scott Pi...  52.29       5
14                          Rip it Up and Start Again  35.02       5
15  Our Band Could Be Your Life: Scenes from the A...  57.25       3
16                                               Olio  23.88       1
17  Mesaerion: The Best Science Fiction Stories 18...  37.59       1
18                       Libertarianism for Beginners  51.33       2
19                            It's Only the Himalayas  45.17       2

In [7]:
df.price.mean()

38.048500000000004

In [12]:
df[df.price < 40]

                                                title  price  rating
5                                     The Requiem Red  22.65       1
6   The Dirty Little Secrets of Getting Your Dream...  33.34       4
7   The Coming Woman: A Novel Based on the Life of...  17.93       3
8   The Boys in the Boat: Nine Americans and Their...  22.60       4
10     Starving Hearts (Triangular Trade Trilogy, #1)  13.99       2
11                              Shakespeare's Sonnets  20.66       4
12                                        Set Me Free  17.46       5
14                          Rip it Up and Start Again  35.02       5
16                                               Olio  23.88       1
17  Mesaerion: The Best Science Fiction Stories 18...  37.59       1

In [18]:
df.to_csv('book.csv', index='False')